services:
  - type: web
    name: mononote
    env: node
    buildCommand: pnpm run build
    startCommand: pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
    healthCheckPath: /

